name: Run Podcast Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./
        with:
          email: ${{ github.actor }}@example.com
          name: ${{ github.actor }}
